version: "3.7"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes: 
      - "$WEIGHT_DIR:/server/weight"
  client:
    build:
      context: ./client
      args: 
        - "API_ADDRESS=$API_ADDRESS"
    ports: 
      - "3000:3000"
